#if CEL == 1
    texture.gbuffers.gaux4 = cel_ramp.png
#endif
#if CEL == 0
    texture.gbuffers.gaux4 = ramp.png
#endif

sliders = THRESHOLD RIM_OFFECT OUTLINE_COL LINEAR_DEPTH PAPER_WORLD OUTLINE_MODE ENABLE_SHADOWS SOFT_SHADOWS Shininess LAMBERT_MODE shadowMapResolution CEL

screen = THRESHOLD RIM_OFFECT OUTLINE_COL LINEAR_DEPTH PAPER_WORLD OUTLINE_MODE ENABLE_SHADOWS SOFT_SHADOWS Shininess LAMBERT_MODE shadowMapResolution CEL

texture.noise = blueNoiseR.png
