texture.gbuffers.gaux3 = texture/cel_ramp.png

texture.gbuffers.gaux4 = texture/ramp.png


sliders = THRESHOLD RIM_OFFECT OUTLINE_COL LINEAR_DEPTH PAPER_WORLD OUTLINE_MODE ENABLE_SHADOWS SOFT_SHADOWS Shininess shadowMapResolution CEL ENABLE_TEXTURE_OUTLINES TEXTURE_OUTLINE_STRENGTH  OUTLINE_THICKNESS SHADOW_DISTANCE

screen = [Shadow] [Outline] [TextureOutline] PAPER_WORLD Shininess CEL 
screen.Shadow = ENABLE_SHADOWS SOFT_SHADOWS shadowMapResolution SHADOW_DISTANCE
screen.Outline = THRESHOLD RIM_OFFECT OUTLINE_COL LINEAR_DEPTH OUTLINE_MODE
screen.TextureOutline = ENABLE_TEXTURE_OUTLINES TEXTURE_OUTLINE_STRENGTH  OUTLINE_THICKNESS

texture.noise = texture/blueNoiseR.png
